# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: google/cloud-sdk:slim

before_script:
    - gcloud compute ssh deimos2 --command "pwd"

pages:
  stage: deploy
  script:
  - echo "deploy"
  only:
  - jekyll

